#lang sicp
(define (smallest-divisor n)
  (find-divisor n 2))
(define (find-divisor n test-divisor)
  (cond ((> (square test-divisor) n) n)
        ((divides? test-divisor n) test-divisor)
        (else (find-divisor n (+ test-divisor 1)))))
(define (divides? a b)
  (= (remainder b a) 0))
(define (square a)
  (* a a))

(define (prime? n)
  (= n (smallest-divisor n)))

(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (if (prime? n)
      (report-prime (- (runtime) start-time))))
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))

(define (search-for-primes start count start-time)
  (cond ( (= count 3) (- (runtime) start-time))
        ( (even? start) (search-for-primes (+ start 1) count start-time))
        ( (prime? start) (search-for-primes (+ start 2) (+ count 1) start-time))
        (  else (search-for-primes (+ start 2) count start-time))))